### ISSUE TITLE
I'm interested in your work, how can I get the prior files?

### ISSUE THREAD

**Issue by rokrokss** [mingdachen/vsl#1]
I'm interested in your work, how can I get the prior files?

**Comment by mingdachen** [comment]
Hi, thanks for your interest! I didn't keep prior files in previous experiments. In my experience, training from scratch should be fine for most of the sequence labeling datasets.

**Comment by rokrokss** [comment]
I think I understood how it works now! By the way, the implementation is very concrete and clever. I'm planning to study with your work here. Thanks for your kind answer.
